version: '1.0.{build}'
image: Visual Studio 2017
configuration:
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_build:
- appveyor-retry dotnet restore -v Minimal
- cd C:\projects\tubular-aspnet-core-boilerplate\src\Unosquare.Tubular.Project
- npm install
build_script:
- dotnet build -c %CONFIGURATION% --no-dependencies

