version: '1.0.{build}'
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
- npm cache clean
- npm install
build_script:
- dotnet build src\Unosquare.Tubular.Project -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
cache:
- '%USERPROFILE%\.nuget\packages'
